// SOURCE DE VÉRITÉ : app.py — 10 questions par module
export interface Question {
  q: string; opts: string[]; correct: number; expl: string
}
export interface QuizModule { moduleId: number; questions: Question[] }

export const QUIZ: QuizModule[] = [
  {
    moduleId: 1,
    questions: [
      { q:"Pourquoi un architecte doit-il maîtriser le design graphique ?", opts:["Pour remplacer les graphistes professionnels","Pour valoriser et présenter lui-même ses projets avec impact","Parce que c\'est imposé par le programme universitaire","Pour créer des logos d\'entreprise"], correct:1, expl:"Le design graphique rend l\'architecte autonome dans la valorisation visuelle de ses projets, sans dépendre d\'un tiers créatif." },
      { q:"Qu\'est-ce que la hiérarchie visuelle ?", opts:["Un style de typographie réservé aux titres","L\'organisation des éléments pour guider l\'œil du plus important au moins important","La disposition des couleurs dans un dégradé","Un principe uniquement applicable aux affiches"], correct:1, expl:"La hiérarchie visuelle guide le regard du spectateur en donnant plus d\'importance aux éléments clés." },
      { q:"Le contraste en design graphique sert principalement à :", opts:["Rendre une composition plus colorée","Créer des différences marquées pour attirer l\'attention et améliorer la lisibilité","Harmoniser les teintes d\'une image","Réduire le nombre de couleurs utilisées"], correct:1, expl:"Le contraste crée des différences visuelles (couleur, taille, forme) qui guident l\'attention et renforcent la lisibilité." },
      { q:"L\'espace négatif dans une composition est :", opts:["Un espace inutilisé qu\'il faut toujours remplir","L\'espace vide autour des éléments, qui participe activement à la composition","Un défaut de mise en page","Uniquement utilisé dans le design minimaliste"], correct:1, expl:"L\'espace négatif est un outil puissant. Il donne de la respiration aux éléments et peut créer des formes ou des significations." },
      { q:"La règle de l\'alignement préconise de :", opts:["Centrer tous les éléments d\'une composition","Aligner chaque élément sur une ligne guide pour créer de l\'ordre et de la cohérence","Disposer les éléments de façon aléatoire","Utiliser uniquement des grilles de 12 colonnes"], correct:1, expl:"L\'alignement crée un ordre visuel invisible mais ressenti. Des éléments alignés donnent une impression de professionnalisme." },
      { q:"Des couleurs complémentaires sont :", opts:["Des couleurs de la même famille","Des couleurs opposées sur le cercle chromatique créant un contraste maximal","Des couleurs qui se ressemblent et créent de l\'harmonie","Uniquement le noir et le blanc"], correct:1, expl:"Les couleurs complémentaires (ex: orange et bleu) sont opposées sur le cercle chromatique. Leur association crée un contraste vibrant." },
      { q:"Le principe de répétition en design consiste à :", opts:["Copier le même élément partout sans réfléchir","Réutiliser des éléments visuels pour créer de la cohérence","Reproduire le travail d\'un autre designer","Utiliser le même format pour tous les documents"], correct:1, expl:"La répétition d\'éléments visuels (couleur, police, forme) renforce la cohérence visuelle et l\'identité d\'une composition." },
      { q:"La composition en design graphique est :", opts:["La technique de création musicale appliquée au visuel","L\'arrangement délibéré des éléments visuels pour créer un tout cohérent","Le nombre de couleurs dans un document","La taille du fichier final exporté"], correct:1, expl:"La composition est l\'art d\'arranger les éléments (texte, image, forme, espace) pour créer une communication visuelle efficace." },
      { q:"Pourquoi est-il indispensable de maîtriser un logiciel de design ?", opts:["Parce que les idées sans exécution technique ne peuvent pas être communiquées visuellement","Parce que les logiciels remplacent la créativité","Pour impressionner les clients avec des termes techniques","Ce n\'est pas indispensable, les idées suffisent"], correct:0, expl:"Une idée brillante mal exécutée visuellement perd son impact. La maîtrise technique est le pont entre la vision créative et la communication efficace." },
      { q:"Le principe de proximité stipule que :", opts:["Les éléments doivent être proche du bord de la page","Des éléments visuellement proches sont perçus comme appartenant au même groupe","La taille doit être proportionnelle à la distance","Les textes doivent toujours être proches des images"], correct:1, expl:"Ce qui est proche est perçu ensemble. En design, regrouper les éléments liés aide l\'œil à comprendre l\'organisation de l\'information." },
    ]
  },
  {
    moduleId: 2,
    questions: [
      { q:"La différence entre une police Serif et Sans-serif est :", opts:["La police Serif est plus moderne","La Serif possède des empattements au bout des lettres, contrairement à la Sans-serif","La Sans-serif est réservée aux titres","Il n\'y a aucune différence significative"], correct:1, expl:"Les empattements (serifs) sont de petits traits décoratifs. Times New Roman est un Serif, Arial est un Sans-serif." },
      { q:"La hiérarchie typographique dans une présentation de projet sert à :", opts:["Utiliser le maximum de polices différentes","Guider le lecteur en distinguant visuellement titres, sous-titres et corps","Rendre le texte plus coloré","Augmenter le nombre de mots par page"], correct:1, expl:"Une hiérarchie claire (taille, graisse, couleur) permet de scanner rapidement un document et de comprendre son organisation." },
      { q:"Le \'pairing\' de polices désigne :", opts:["L\'utilisation d\'une seule police","L\'association harmonieuse de deux polices qui se complètent sans se concurrencer","La copie d\'une police existante","Le redimensionnement d\'une police"], correct:1, expl:"Un bon pairing associe une police de titre expressive à une police de corps lisible. Ex: Syne (titre) + Inter (corps)." },
      { q:"L\'interlignage (line-height) désigne :", opts:["L\'espacement horizontal entre les lettres","L\'espacement vertical entre les lignes de texte","La largeur d\'une colonne de texte","Le nombre de lignes par paragraphe"], correct:1, expl:"Un interlignage trop serré étouffe le texte, trop grand le fragmente. La règle : 1.4-1.6x la taille de la police." },
      { q:"Combien de familles de polices dans une présentation professionnelle ?", opts:["Le plus possible","1 à 2 familles maximum, avec variations pour la hiérarchie","5 à 6 familles pour diversifier","Aucune règle n\'existe"], correct:1, expl:"Trop de polices crée de la cacophonie visuelle. 1 à 2 familles suffisent — les variations (taille, graisse, couleur) créent la diversité." },
      { q:"La lisibilité d\'un texte est principalement affectée par :", opts:["Le prix du logiciel utilisé","Le contraste texte/fond, la taille et la police choisie","Le nombre de mots dans le document","La date de création du fichier"], correct:1, expl:"Un texte difficile à lire ne sera pas lu. Le contraste, la taille, la police et l\'interlignage sont déterminants." },
      { q:"L\'interlettrage (tracking) désigne :", opts:["L\'espacement entre les paragraphes","L\'espacement entre les caractères d\'un texte","La hauteur des majuscules","La largeur des marges"], correct:1, expl:"Un tracking large sur des titres en majuscules crée un effet élégant et aéré." },
      { q:"Pourquoi la typographie est-elle un outil de communication à part entière ?", opts:["Parce qu\'elle est obligatoire","Parce que le choix de police transmet une émotion avant même que le texte soit lu","Parce que les typographes sont bien payés","Parce qu\'elle remplace les images"], correct:1, expl:"Avant de lire un mot, on perçoit la police. La typographie est le premier message reçu." },
      { q:"La structure typographique la plus efficace pour une affiche est :", opts:["Tout en majuscules avec une seule taille","Un titre dominant, un sous-titre intermédiaire, un corps en petite taille lisible","Tout en italique pour un effet dynamique","Alterner gras et fin sans logique"], correct:1, expl:"La hiérarchie à 3 niveaux (titre / sous-titre / corps) est le fondement de toute présentation efficace." },
      { q:"Une police \'display\' est :", opts:["Une police pour écran uniquement","Une police expressive pour grands formats, pas adaptée aux petits corps de texte","Une police d\'imprimante sans licence","Une police qui s\'adapte à l\'écran"], correct:1, expl:"Les polices display (Syne, Bebas Neue) ont des détails expressifs pour les titres. En petite taille, elles deviennent illisibles." },
    ]
  },
  {
    moduleId: 3,
    questions: [
      { q:"Dans Photoshop, un calque (layer) est :", opts:["Un filtre de couleur appliqué à toute l\'image","Une couche indépendante superposable permettant d\'éditer des éléments séparément","Un outil de sélection avancé","Le format d\'export du fichier"], correct:1, expl:"Les calques sont le fondement de Photoshop. Ils permettent de travailler de façon non-destructive." },
      { q:"Un masque de fusion (layer mask) permet de :", opts:["Fusionner définitivement deux calques","Cacher ou révéler des parties d\'un calque de façon non-destructive (noir=cacher, blanc=révéler)","Changer la couleur d\'un calque","Verrouiller un calque"], correct:1, expl:"Le masque est non-destructif : il cache les pixels sans les supprimer. C\'est l\'outil de découpe le plus professionnel." },
      { q:"La différence entre RVB et CMJN est :", opts:["Il n\'y a aucune différence visible","RVB est pour l\'écran (lumière additive), CMJN est pour l\'impression (encres soustractives)","CMJN contient plus de couleurs que RVB","RVB uniquement pour les photos"], correct:1, expl:"Travailler en RVB pour l\'impression entraîne des décalages de couleurs. Toujours choisir le bon mode dès la création." },
      { q:"L\'outil \'Sélection rapide\' est utile pour :", opts:["Sélectionner des calques dans le panneau","Détecter automatiquement et sélectionner des zones aux contours définis","Dupliquer une sélection existante","Créer une nouvelle fenêtre"], correct:1, expl:"L\'outil de sélection rapide utilise l\'intelligence de Photoshop pour détecter les bords et sélectionner des zones cohérentes." },
      { q:"Un Smart Object (objet dynamique) permet de :", opts:["Réduire automatiquement la taille du fichier","Redimensionner et transformer un élément sans perte de qualité","Générer automatiquement des effets de texte","Synchroniser avec Illustrator"], correct:1, expl:"Un Smart Object préserve les données originales. Toutes les transformations et filtres restent modifiables." },
      { q:"Pour exporter une photo destinée au web, le format le plus adapté est :", opts:["PSD (conserver les calques)","JPEG (compression efficace pour photos)","SVG (résolution infinie)","BMP (universel sans compression)"], correct:1, expl:"JPEG compresse efficacement les photos. PNG est préférable pour la transparence. PSD est le format de travail, pas d\'export." },
      { q:"L\'outil \'Courbes\' (Curves) permet de :", opts:["Dessiner des courbes et formes","Ajuster précisément la luminosité et le contraste sur toute la gamme tonale","Créer des effets de flou en courbe","Modifier la forme des calques"], correct:1, expl:"Les Courbes sont l\'outil de correction colorimétrique le plus puissant. Elles contrôlent indépendamment les tons sombres, moyens et clairs." },
      { q:"Pourquoi maîtriser les calques est-il prioritaire dans Photoshop ?", opts:["Parce que c\'est la première rubrique du menu","Parce que tout le flux professionnel repose sur une gestion organisée permettant des modifications non-destructives","Parce que les calques compriment les fichiers","Ce n\'est pas prioritaire"], correct:1, expl:"Un fichier professionnel est un empilement organisé de calques nommés et groupés." },
      { q:"La résolution 300 DPI est requise pour :", opts:["L\'affichage sur écran HD","L\'impression de qualité professionnelle (affiches, flyers, livrets)","Les vidéos en 4K","Les publications sur réseaux sociaux"], correct:1, expl:"72 DPI suffit pour l\'écran, 300 DPI est le standard pour l\'impression professionnelle." },
      { q:"Le mode de fusion \'Multiplier\' (Multiply) produit :", opts:["Un éclaircissement de l\'image","Un assombrissement — idéal pour les ombres et textures","Une transparence totale","Une inversion des couleurs"], correct:1, expl:"Multiplier est très utilisé pour ajouter des ombres naturelles ou texturer des surfaces. Le blanc est invisible en mode Multiplier." },
    ]
  },
  {
    moduleId: 4,
    questions: [
      { q:"Un mockup en design graphique est :", opts:["Une maquette d\'architecture en 3D","Une mise en situation réaliste d\'un visuel sur un support (affiche, téléphone, t-shirt)","Un brouillon dessiné à la main","Un modèle de facture"], correct:1, expl:"Le mockup permet de visualiser un design dans son contexte réel. Indispensable pour convaincre un client." },
      { q:"Pour une affiche percutante, quel élément doit dominer ?", opts:["Le logo de l\'école","Un titre fort et une image centrale de haute qualité","La liste exhaustive des intervenants","Un maximum de texte explicatif"], correct:1, expl:"Une affiche a 2-3 secondes pour capter l\'attention. Le titre et l\'image principale doivent communiquer l\'essentiel instantanément." },
      { q:"Le format story Instagram (1080x1920px) a un ratio de :", opts:["1:1 (carré)","9:16 (portrait vertical)","16:9 (paysage horizontal)","4:3 (photo classique)"], correct:1, expl:"Le ratio 9:16 est le format vertical plein écran des smartphones." },
      { q:"La maîtrise de Photoshop est un avantage concurrentiel car :", opts:["Elle permet de ne plus avoir besoin d\'ordinateur puissant","Elle permet de créer ses visuels de communication sans attendre un graphiste externe","Elle permet d\'automatiser ses calculs","Elle réduit le temps de construction"], correct:1, expl:"Un architecte qui maîtrise Photoshop est autonome pour valoriser son travail." },
      { q:"La cohérence visuelle d\'une planche de présentation repose sur :", opts:["L\'utilisation de couleurs vives et variées","Une palette cohérente, une grille de mise en page et des polices homogènes","Un nombre élevé d\'images","La présence de nombreux logos"], correct:1, expl:"La cohérence visuelle signale la maîtrise et le professionnalisme." },
      { q:"Pour un visuel grand format, la résolution doit être :", opts:["72 DPI — suffisant pour tout usage","150 à 300 DPI selon la distance de lecture","600 DPI minimum pour tous les grands formats","La résolution n\'a pas d\'importance"], correct:1, expl:"Pour une bâche vue de loin, 72-100 DPI peut suffire. Pour une affiche A3-A2 vue de près, 150-300 DPI est nécessaire." },
      { q:"Le \'storytelling visuel\' d\'une présentation désigne :", opts:["L\'illustration d\'une histoire fictive","La construction d\'un récit visuel logique de la problématique à la solution","La description textuelle du projet","L\'utilisation exclusive de photos"], correct:1, expl:"Un bon storytelling structure la présentation comme un récit : contexte → problème → concept → solution → résultat." },
      { q:"La bonne pratique pour créer un visuel pour réseaux sociaux est :", opts:["Créer un seul format et recadrer","Créer un document dans les dimensions exactes de la plateforme en RVB 72 DPI dès le début","Toujours travailler en CMJN","Utiliser des polices en-dessous de 12px"], correct:1, expl:"Créer le bon format dès le début évite les recadrages. RVB 72 DPI pour le digital allège le fichier." },
      { q:"L\'effet de double exposition est réalisé via :", opts:["L\'outil de flou gaussien","La superposition de calques avec des modes de fusion et des masques","Un filtre automatique dans le menu Effets","La fonction de duplication de calque"], correct:1, expl:"La double exposition combine deux images via modes de fusion et masques." },
      { q:"Un template (gabarit) Photoshop est utile car :", opts:["C\'est un document vierge sans mise en forme","C\'est un fichier PSD structuré et réutilisable garantissant cohérence visuelle","C\'est un filtre prédéfini","C\'est un type d\'export spécial"], correct:1, expl:"Un bon template contient grille, zones de texte, palette et styles typographiques. Il accélère considérablement la production." },
    ]
  },
  {
    moduleId: 5,
    questions: [
      { q:"Une charte graphique est :", opts:["Un contrat légal","Un document de référence définissant les règles visuelles d\'une identité","Un logiciel de création","Une liste de prix"], correct:1, expl:"La charte graphique est la bible visuelle d\'une marque. Elle garantit la cohérence de toutes les communications." },
      { q:"Pourquoi définir une palette de couleurs limitée ?", opts:["Pour économiser de l\'encre","Pour créer une cohérence visuelle immédiatement reconnaissable","Parce que les logiciels limitent les couleurs","Pour suivre les tendances"], correct:1, expl:"Une palette réduite (2-4 couleurs) crée une identité forte et reconnaissable." },
      { q:"Le moodboard est utilisé en début de projet pour :", opts:["Présenter le budget au client","Définir et communiquer l\'ambiance visuelle avant de créer quoi que ce soit","Lister les logiciels utilisés","Montrer les projets précédents"], correct:1, expl:"Le moodboard aligne les parties prenantes sur une vision commune avant de commencer." },
      { q:"Dans un pitch visuel, les 3 premières secondes servent à :", opts:["Lire le sommaire du projet","Créer une première impression émotionnelle forte","Présenter les membres de l\'équipe","Expliquer le contexte réglementaire"], correct:1, expl:"L\'image d\'ouverture et l\'ambiance visuelle doivent créer une émotion avant même que le mot soit prononcé." },
      { q:"Un pitch deck visuel de projet est :", opts:["Un ensemble de plans techniques","Une présentation visuelle synthétique qui communique l\'essence et la valeur du projet","Un portfolio exhaustif","Une fiche de données techniques"], correct:1, expl:"Un pitch deck n\'est pas un dossier technique — c\'est une histoire condensée. 10-15 diapositives essentielles." },
      { q:"Les variations de logo dans une charte définissent :", opts:["Les différentes tailles autorisées","Les versions acceptées selon les contextes (fond clair, fond sombre, monochrome, taille minimale)","Les animations autorisées","Le coût de création"], correct:1, expl:"Un logo doit fonctionner dans tous les contextes. La charte définit ces variations pour garantir la cohérence." },
      { q:"Pourquoi un étudiant doit-il savoir créer son identité visuelle ?", opts:["Pour décorer son portfolio","Pour valoriser professionnellement ses projets et être perçu comme crédible","Parce que c\'est une obligation légale","Pour remplacer les bureaux d\'architectes"], correct:1, expl:"Une identité soignée signale le sérieux et la maîtrise." },
      { q:"Le brand storytelling consiste à :", opts:["Inventer une histoire fictive","Construire une narrative authentique qui crée une connexion émotionnelle","Écrire les textes d\'un site web","Créer un roman graphique"], correct:1, expl:"Le storytelling transforme un projet en expérience. On raconte une histoire : l\'origine, les valeurs, la vision." },
      { q:"Pour présenter un projet à un jury, quelle approche est la plus efficace ?", opts:["Présenter le maximum de variantes","Sélectionner les 3-5 éléments les plus forts en expliquant les choix créatifs","Laisser le jury découvrir seul","Imprimer tout en très grand format"], correct:1, expl:"Moins mais mieux : un jury préfère 5 éléments forts à 50 éléments médiocres." },
      { q:"La planche de style se différencie du moodboard car elle :", opts:["Contient uniquement des photos d\'inspiration","Présente les éléments concrets de l\'identité (palette précise, polices réelles, textures)","Est destinée uniquement aux sites web","Ne comprend jamais de texte"], correct:1, expl:"Le moodboard est émotionnel. La planche de style est concrète : les vrais codes visuels du projet." },
    ]
  },
  {
    moduleId: 6,
    questions: [
      { q:"Adobe Firefly est principalement utilisé pour :", opts:["Monter des vidéos professionnelles","Générer des images, textures et effets via des prompts en langage naturel","Créer des animations","Gérer les fichiers Creative Cloud"], correct:1, expl:"Adobe Firefly est le moteur de génération d\'images d\'Adobe. Il génère des images et remplit intelligemment des zones." },
      { q:"Un prompt efficace pour générer une image doit contenir :", opts:["Un seul mot clé précis","Une description détaillée du sujet, style visuel, ambiance, lumière et format","Des mots en majuscules","Uniquement des adjectifs"], correct:1, expl:"Un bon prompt décrit : sujet + style artistique + lumière + ambiance + format. Plus le prompt est précis, meilleur le résultat." },
      { q:"L\'automatisation améliore le workflow design en :", opts:["Remplaçant complètement la créativité humaine","Accélérant les tâches répétitives pour libérer du temps pour la création à haute valeur ajoutée","Supprimant la nécessité d\'apprendre les logiciels","Produisant automatiquement des chartes graphiques"], correct:1, expl:"Ces outils excellent dans les tâches répétitives, libérant le designer pour la stratégie et la créativité." },
      { q:"La suppression d\'arrière-plan automatique est utile pour :", opts:["Améliorer la résolution","Extraire rapidement des sujets de leur fond pour les intégrer dans des compositions","Convertir une image en vecteur","Corriger l\'exposition"], correct:1, expl:"Ces outils réalisent en secondes ce qui prenait des minutes. Indispensable pour les compositions rapides." },
      { q:"Pourquoi ces outils sont-ils pertinents pour les débutants ?", opts:["Parce qu\'ils valident les projets automatiquement","Parce qu\'ils permettent de générer rapidement des références visuelles et des variations créatives","Parce qu\'ils remplacent les formateurs","Parce qu\'ils sont gratuits"], correct:1, expl:"Pour un débutant, ces outils sont un accélérateur de vision. Ils permettent d\'explorer des directions créatives." },
      { q:"Le remplissage génératif (Generative Fill) de Photoshop permet de :", opts:["Remplir tous les calques vides","Étendre ou modifier une image en générant du contenu qui s\'intègre naturellement","Créer des motifs géométriques","Remplir une sélection avec une couleur unie"], correct:1, expl:"Le remplissage génératif analyse le contexte et génère du contenu cohérent." },
      { q:"La limite principale de ces outils dans le workflow est :", opts:["Ils ne fonctionnent pas avec Photoshop","Ils ne remplacent pas le jugement créatif, la sensibilité culturelle et la direction artistique","Ils produisent des images de mauvaise qualité","Ils sont trop lents"], correct:1, expl:"Ces outils génèrent mais ne comprennent pas. Ils ne savent pas si une couleur est culturellement appropriée." },
      { q:"Pour un moodboard créatif efficace, la meilleure approche est :", opts:["Générer une seule image parfaite","Générer plusieurs variations, sélectionner les plus pertinentes et assembler","Utiliser uniquement des images de Google","Laisser l\'outil choisir seul"], correct:1, expl:"Le moodboard est un outil d\'exploration : générer des dizaines de variations rapidement, puis exercer son œil critique." },
      { q:"La vectorisation automatique permet de :", opts:["Convertir une image bitmap en fichier vectoriel SVG ou AI de bonne qualité","Animer automatiquement des images","Compresser des fichiers vectoriels","Changer les couleurs d\'un logo"], correct:0, expl:"Des outils analysent une image bitmap et génèrent une version vectorielle scalable. Très utile pour convertir des croquis scannés." },
      { q:"Intégrer ces outils dans son workflow crée un avantage car :", opts:["Ils permettent de travailler sans effort","Ils multiplient la vitesse d\'exécution tout en maintenant la qualité créative","Ils éliminent le besoin d\'apprendre les fondamentaux","Ils garantissent le même résultat pour tous"], correct:1, expl:"Un designer qui maîtrise ces outils produit en 1 heure ce qu\'un autre fait en 4. Cette efficacité libère du temps pour la créativité." },
    ]
  },
  {
    moduleId: 7,
    questions: [
      { q:"La différence entre image vectorielle et image matricielle (bitmap) est :", opts:["L\'image vectorielle est toujours plus lourde","L\'image vectorielle est définie par des équations mathématiques, scalable à l\'infini sans perte","L\'image bitmap peut être agrandie sans limite","Il n\'y a aucune différence visible"], correct:1, expl:"Un vecteur est mathématique : agrandir un logo de 1cm à 10m ne crée aucun flou. Un bitmap pixelise à l\'agrandissement." },
      { q:"Adobe Illustrator est le logiciel idéal pour créer :", opts:["Des montages photo complexes","Des logos, icônes, illustrations destinés à différentes tailles","Des vidéos et animations","Des maquettes de sites web interactives"], correct:1, expl:"Illustrator est le roi du vecteur. Logos, pictogrammes, illustrations — tout ce qui doit être scalable et précis." },
      { q:"L\'outil Plume (Pen Tool) dans Illustrator est utilisé pour :", opts:["Écrire du texte","Tracer des courbes et lignes précises point par point, avec contrôle des tangentes","Sélectionner des objets","Peindre des zones de couleur"], correct:1, expl:"L\'outil Plume est le plus puissant d\'Illustrator. Il permet de créer n\'importe quelle forme avec une précision absolue." },
      { q:"Pour exporter un logo avec transparence destiné au web, le format recommandé est :", opts:["JPEG (haute qualité)","SVG (vectoriel) ou PNG (haute résolution avec transparence)","PSD (Photoshop)","BMP (Windows Bitmap)"], correct:1, expl:"SVG est l\'idéal pour le web : vectoriel, léger, scalable et transparent. JPEG ne supporte pas la transparence." },
      { q:"Quand faut-il utiliser Illustrator plutôt que Photoshop ?", opts:["Pour retoucher des photos","Pour créer des éléments graphiques utilisés à différentes tailles : logos, icônes","Pour créer des effets de lumière réalistes","Pour monter des vidéos"], correct:1, expl:"Règle simple : si l\'élément doit être scalable → Illustrator. Si c\'est une image à éditer → Photoshop." },
      { q:"Les formes composées dans Illustrator (Pathfinder) permettent de :", opts:["Regrouper des formes pour les déplacer","Combiner plusieurs formes pour créer des formes complexes (union, soustraction, intersection)","Appliquer le même remplissage à plusieurs formes","Créer des ombres portées"], correct:1, expl:"Le Pathfinder permet des formes impossibles autrement : soustraire un cercle d\'un carré, unir deux formes." },
      { q:"Le format de fichier natif Illustrator (.AI) est important car il :", opts:["Est le seul format accepté par les imprimeries","Conserve tous les calques, tracés et éléments modifiables","Compresse les fichiers","Permet de partager sans logiciel Adobe"], correct:1, expl:"Le fichier .AI est le format de travail. Pour partager, on exporte en PDF, SVG ou PNG." },
      { q:"Pourquoi tous les logos professionnels doivent-ils être créés en vectoriel ?", opts:["Pour que les logiciels les chargent plus vite","Parce qu\'un logo s\'utilise à toutes les tailles — du favicon à la bâche de 10m","Parce que le format vectoriel est moins cher","Pour respecter des normes ISO"], correct:1, expl:"Un logo bitmap agrandit devient flou. Un logo vectoriel reste parfait à n\'importe quelle taille." },
      { q:"La grille et les repères dans Illustrator servent à :", opts:["Décorer l\'espace de travail","Aligner précisément les éléments et maintenir une cohérence géométrique rigoureuse","Ajouter des effets de texture","Calculer les dimensions automatiquement"], correct:1, expl:"La précision est la valeur fondamentale du vectoriel. Les repères permettent d\'aligner des éléments au pixel près." },
      { q:"L\'objectif final de la formation Ascension est :", opts:["Maîtriser tous les logiciels Adobe à un niveau expert","Être capable de concevoir, produire et présenter de façon autonome des visuels qui valorisent ses projets","Créer le plus de designs possible","Imiter le style des grands designers"], correct:1, expl:"L\'objectif d\'Ascension n\'est pas la maîtrise technique pure — c\'est l\'autonomie créative. Sortir capable de se présenter visuellement au monde." },
    ]
  },
]

export const getQuiz = (moduleId: number) => QUIZ.find(q => q.moduleId === moduleId)
